//user
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER'
export const ALL_USERS_DATA='ALL_USERS_DATA'
export const ALL_PROCESSED_CSV='ALL_PROCESSED_CSV'